# Generated by Django 5.2.4 on 2025-07-08 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Danışan Adı')),
                ('date', models.DateTimeField(verbose_name='Tarih ve Saat')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('done', 'Yapıldı'), ('canceled', 'İptal')], default='planned', max_length=10, verbose_name='Durum')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
