# Generated by Django 5.2.4 on 2025-07-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sari_seans', '0002_commissionrate_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrate',
            name='name',
            field=models.CharField(default='Genel Kesinti', max_length=100, verbose_name='Kesinti Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psychologist',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Kesinti Oranı (%)'),
        ),
        migrations.AddField(
            model_name='session',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Nakit'), ('credit_card', 'Kredi Kartı'), ('debit_card', 'Banka Kartı'), ('bank_transfer', 'Banka Transferi')], default='cash', max_length=20, verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('online', 'Online Seans'), ('face_to_face', 'Yüz Yüze Seans')], default='face_to_face', max_length=20, verbose_name='Seans Türü'),
        ),
    ]
