# Generated by Django 5.2.4 on 2025-07-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sari_seans', '0003_commissionrate_name_psychologist_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20, unique=True, verbose_name='Ödeme Yöntemi')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ek Kesinti Oranı (%)')),
            ],
            options={
                'verbose_name': 'Ödeme Yöntemi Ek Kesinti',
                'verbose_name_plural': 'Ödeme Yöntemi Ek Kesintiler',
            },
        ),
        migrations.CreateModel(
            name='SessionTypeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(max_length=20, unique=True, verbose_name='Seans Türü')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ek Kesinti Oranı (%)')),
            ],
            options={
                'verbose_name': 'Seans Türü Ek Kesinti',
                'verbose_name_plural': 'Seans Türü Ek Kesintiler',
            },
        ),
    ]
