# Generated by Django 5.2.4 on 2025-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sari_seans', '0005_psychologist_extra_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='extra_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bu seans için özel ek kesinti oranı', max_digits=5, verbose_name='Ek Kesinti Oranı (%)'),
        ),
    ]
