# Generated by Django 5.2.4 on 2025-07-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sari_seans', '0007_assistant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommissionRate',
        ),
    ]
